// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250815031324_AddPaymentFieldsToOrder")]
    partial class AddPaymentFieldsToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Randal Hermiston"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Renee Klocko"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Corey Wisoky"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Clayton Satterfield"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ben Fay"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Trevor Hintz"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Randolph Lowe"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cathy O'Keefe"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Wendy Abernathy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Elsa Rodriguez"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cecelia Glover"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Luz Becker"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Elisa Miller"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Jeremiah Goodwin"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Beth Durgan"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cecilia Hilpert"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Leslie Ziemann"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Jose Okuneva"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Verna Goldner"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Samantha Paucek"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasMaxLength(32)
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tasty Cotton Salad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Small Frozen Gloves"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Refined Rubber Soap"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Awesome Frozen Chair"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Handcrafted Concrete Gloves"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rustic Cotton Table"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Generic Frozen Ball"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Intelligent Plastic Salad"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantastic Granite Salad"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Licensed Soft Computer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gorgeous Frozen Ball"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tasty Frozen Tuna"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ergonomic Concrete Keyboard"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Small Concrete Chips"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Gorgeous Cotton Chair"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Licensed Rubber Computer"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Rustic Plastic Pizza"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Rustic Granite Salad"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Practical Concrete Soap"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Handmade Wooden Bacon"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
